/**
 * LISTA DE CIDADES DOADORAS - ATUALIZAÇÃO AUTOMÁTICA
 * Arquivo gerado via painel administrativo em 25/05/2026, 14:44:07
 * Substitua este arquivo na pasta do seu repositório no GitHub para publicar globalmente.
 */

const cidadesDoadorasIniciais = [
  "Abreu e Lima",
  "Afogados da Ingazeira",
  "Água Preta",
  "Águas Belas",
  "Altinho",
  "Arcoverde",
  "Barreiros",
  "Belém de São Francisco",
  "Belo Jardim",
  "Bezerros",
  "Bom Conselho",
  "Cabo de Santo Agostinho",
  "Caetés",
  "Camaragibe",
  "Carnaíba",
  "Carpina",
  "Caruaru",
  "Catende",
  "Cedro",
  "Chã de Alegria",
  "Chã Grande",
  "Cupira",
  "Escada",
  "Exu",
  "Feira Nova",
  "Ferreiros",
  "Floresta",
  "Garanhuns",
  "Goiana",
  "Gravatá",
  "Igarassu",
  "Ilha de Itamaracá",
  "Ipojuca",
  "Itapetim",
  "Itapissuma",
  "Jaboatão dos Guararapes",
  "Jatobá",
  "Lajedo",
  "Limoeiro",
  "Mirandiba",
  "Moreno",
  "Olinda",
  "Ouricuri",
  "Palmares",
  "Palmeirina",
  "Panelas",
  "Paulista",
  "Pesqueira",
  "Petrolina",
  "Pombos",
  "Recife",
  "Sairé",
  "Sanharó",
  "Santa Cruz do Capibaribe",
  "São Caitano",
  "São José do Egito",
  "São Lourenço da Mata",
  "São Vicente Ferrer",
  "Serra Talhada",
  "Surubim",
  "Tabira",
  "Taquaritinga do Norte",
  "Timbaúba",
  "Triunfo",
  "Tupanatinga",
  "Venturosa",
  "Vicência",
  "Vitória de Santo Antão"
];
